### ISSUE TITLE
Printing from PDF

### ISSUE THREAD

**Issue by rangathedon** [python-escpos/python-escpos#377] opened 2020-02-21 11:01 UTC
Can this library be used to print a pdf file directly to the printer? could not find any example on the same; please help

**Comment by rangathedon** [comment] 2020-02-21 11:04
Posted earlier https://github.com/python-escpos/python-escpos/issues/376 but it was closed without even understanding the question

**Comment by patkan** [comment] 2020-02-21 11:14
duplicate of #376

**Closed by patkan** 2020-02-21 11:14 UTC

**Comment by rangathedon** [comment] 2020-02-21 14:07
> 
> 
> duplicate of #376

really ridiculous, you are closing it as duplicate without understanding the issue :-(

**Comment by patkan** [comment] 2020-02-21 14:14
I do not know why it should be ridiculuos to close a duplicate. After you have added additional information, I have reopened #376, so why should I keep this issue?

**Comment by rangathedon** [comment] 2020-02-21 14:59
how would I know if it was reopened? It wasnt when I posted the other one;
thanks for the response on the other issue :-)
