### ISSUE TITLE
Image printing not working on Epson TM U220

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-escpos/python-escpos#42] opened 2015-03-17 01:20 UTC
```
What steps will reproduce the problem?
1. Connect the printer to the USB bus. The printer is an Epson TM U220
2. Initialize the printer via Epson = printer.Usb instruction 
3. Execute a Epson.image instruction on any kind of image file, format or size

What is the expected output? What do you see instead?

The image should be printed in paper. A large series of ASCII chars are printed 
instead.

What version of the product are you using? On what operating system?


I am using it on Ubuntu 12.04. Text printing works just fine. I have tried 
different image formats, sizes, etc and the error is always the same. 

```

Original issue reported on code.google.com by `Reloadgu...@gmail.com` on 19 Feb 2015 at 10:17

**Comment by boshkash1151** [comment] 2015-07-03 11:22
I had a similar problem. I solved it by printing and empty line before each image.

theprinter = printer.Usb(0x0000,0x0000)
theprinter.text("\n")
theprinter.image("my_image.jpg")
theprinter.text("\n")


Also png with transparent backgrounds caused an issue. 
Credits go to piniyini (https://github.com/manpaz/python-escpos/issues/51)

**Comment by mikrogroove** [comment] 2015-07-28 15:17
I'm having the same problem, but with an Epson TM-U295. Looking at constants.py I see that bit-image printing mode is selected with `1D 76 30 00`, while the TM-U295 ESC/POS command reference says it should be `1B 2A 00 00 01` - where the third byte is print mode (TM-U295 only supports 0 or 1 here), fifth is width multiplier (x256), and fourth is width remainder (IIUC). From the TM-U295 manual: 

![epson tm-u295 bit-image mode](https://cloud.githubusercontent.com/assets/196348/8935345/28fff5e0-3544-11e5-8ee2-b3f7fd35e8fe.png)

**Comment by manpaz** [comment] 2015-08-22 20:12
@mikrogroove , 
Thank you for your interest in the project.
Seems like there has been some issues with transparent images when trying to convert them to RGB. I've committed a fix that hope helps to solve this issue to some many having garbage printed when trying to print RGBA images.

Do you mind to checkout the recent code, do your tests again, and check if you still have the same issues printing images please?

Thank you!

**Comment by mikrogroove** [comment] 2015-10-02 22:54
@manpaz Apologies for taking so long to respond - this is just something I'm tinkering with a little on and off so haven't had a chance until today to test out the updated code - thanks for this btw! I should mention that the image I'm using while testing isn't an RGB(A) image, but a two colour bitmap (one bit). I figured it would make more sense to feed this printer monochrome images since that's all it can produce. In any case, I checked out the latest code and have done some further testing with it. Alas, after trying a few different initialisation strings (I think for this printer `escpos.S_RASTER_N` should be just `\x1b\x2a\x00`?), and a few different image formats (RGB PNG, JPEG, GIF), I still only get output like this: 

![with_command](https://cloud.githubusercontent.com/assets/196348/10259404/94f48500-695f-11e5-9e7c-38722346f1c4.png)

I've looked at your code, but particularly the `convert_image` function passes some distance over my head with a mathematical swoosh. Clearly, something is causing the printer from failing to enter (or exiting) bit image mode. Since my five dot example above works, could it be that the issue is with the size calculation, or the image conversion?

**Comment by patkan** [comment] 2016-03-04 16:48
So far I have found out that in some cases the printer does not seem to be in printing-mode.
For example with some pictures or when in flipped-text mode.

But I could not yet take a closer look at the output.

**Comment by patkan** [comment] 2016-03-11 10:23
@mikrogroove I have read in the command specification and now understand the problem. You were right, the command is wrong.
What we issue is `GS v 0`, which is an obsolete command to enter bit-image-mode. This command is not supported by e.g. TM-U220.
I think we will have to rework this in the future.

**Comment by mikrogroove** [comment] 2016-03-14 17:50
@patkan That's most excellent news, thank you very much for looking into it! So if I wanted to change the command that gets sent, what should I set it to? I'm afraid I don't understand what you mean by `GS v 0`... I haven't given up on making this printer work, and I've got a pretty cool idea for what to use it for, but I do need bit image mode printing.

**Comment by patkan** [comment] 2016-03-14 22:13
Epson has defined different commands for entering bit image mode over time.

An old command is [`GS v 0`](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=94) (ESC/POS is basically plain ASCII-code, that's why the commands can be written as ASCII-sequences)

The new command is [`ESC *`](https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=88).

I am sorry, for the links you have to create an account with Epson. The command reference is, however, quite good.

Another option would be to store the image in the NV memory of the printer. However this memory will not survive continously writing to it. (It will fail soon, this function is intended for store brands and ads.) Moreover this function is not implemented at all in our library ;-) So, bit-image-mode is probably the way to go.

So what has to be done is checking in which way the two commands differ and then patching the print function accordingly.

**Comment by clickworkorange** [comment] 2016-03-14 23:43
Ok, but if you look a bit higher up in the thread, I posted a grab from the TM-U295 manual, which quite clearly states that the bit-image-mode command is `ESC *`

**Comment by patkan** [comment] 2016-03-14 23:48
Yeah, that's what I am saying.
We have to check if the older printers support the new command and if they do, simply replace the commands. For this one has to check the reference in order to know what changed, since the function in python-escpos uses the old command.
If older printers do not support the new command we have to think of a way to support both commands.

**Comment by mike42** [comment] 2016-03-15 10:46
Re getting this working, I think some snippets from mike42/escpos-php#35 will help here. A TM-U220B single-density bit image print-out (using `ESC *`), as an example:

![2016-03-tux](https://cloud.githubusercontent.com/assets/2080552/13774422/15f330c4-eaf3-11e5-816b-33e632af825e.jpg)

`ESC *` prints out the image in a series of rows, and needs some line feed trickery to work the same between printers ('feed n pixels' after each row). The command works on the older Epson U220B, newer TM-T20 and low-end Zijian ZJ5890T (which support double-density graphics, unlike the TM U220).

The source files for this implementation are:
- [EscposImage.php::toColumnFormat()](https://github.com/mike42/escpos-php/blob/81fc60c57d422bbfb92bf21517555d58877ef213/src/Mike42/Escpos/EscposImage.php)
- [Printer.php::bitImageColumnFormat()](https://github.com/mike42/escpos-php/blob/81fc60c57d422bbfb92bf21517555d58877ef213/src/Mike42/Escpos/Printer.php)

I can prepare a python port of this method you would be open to including it.

**Comment by patkan** [comment] 2016-03-16 14:54
@mike42 Thank you! This project is always open to contributions, so we would be happy to include yours.

@python-escpos/dev is anybody working on image-printing? If so, please contact @mike42 

I think this might be connected to #64

**Comment by mike42** [comment] 2016-03-26 13:32
Still making progress on this-

I've just finished testing fresh implementations of ESC/POS image handling as standalone snippets, including `GS v 0` and `ESC *`, see [image-ports](https://github.com/mike42/escpos-snippets/tree/master/image-ports) for current state of things. At this stage it looks like escpos-php users will get a 6x speed-up on raster images, while python-escpos will have a 26x speed-up (scatter plot of rendering times over an 118 image test set: [plot.pdf](https://github.com/python-escpos/python-escpos/files/190490/plot.pdf)). This also relates to #79.

Adding these properly into both drivers with test cases will take a bit of time, but you can expect a pull request to this project in the next few weeks.

**Comment by clickworkorange** [comment] 2016-04-02 14:49
@mike42 Great stuff, I appreciate your efforts on this!

**Closed** 2016-06-24 09:20 UTC
Labels: bug, fixed-in-dev

**Comment by lite1979** [comment] 2018-12-19 05:39
@mike42 

Just an FYI for anyone who stumbles upon this thread:

 Star TSP 650 problem was a dip switch that changed the printer from Star Line Mode to ESC/POS.

**Comment by lucasvog** [comment] 2019-01-19 15:00
Sorry to comment so late on this issue, but on the latest release it still seems not to work on the TM U220 (I have the TM-U220PB). Sadly I am not that experienced in this topic. 
I tried 
`p.image("logo.jpg", impl="bitImageColumn")`
`p.image("logo.jpg")`
and everything inbetween, like converting the image to `.to_column_format()` or `.to_column_format(False)` and looping through the blobs and printing it out with `._raw(row)`
But it all just comes out as garbage. I printed out the binary to the console and I can see that the Image is processed correctly, but not printed out.

Also I tried all the above mentioned examples, it all just prints out symbols. Sadly, the [Documentation](https://python-escpos.readthedocs.io/en/latest/) did not give much information about images. 

@mike42 Thank you very much for all of your efforts. As you helped to rewrite the image handling, I thought that it is now part of this repo, am I wrong?
Is it possible to print an image on the T-U220 with this python package?
