### ISSUE TITLE
Align left and right on the same line

### ISSUE THREAD

**Issue by praneshvrp1396** [python-escpos/python-escpos#418] opened 2020-10-05 20:30 UTC
### Bug description
Need to know a way to have both left and right alignments in the same line.

### Steps to reproduce
- printer.set(align='left')
-printer.text('Name')
-printer.set(align='right')
-printer.text('Qty')

Need my print like:
Name [space][space][space]Qty

But I get the result as:
Name[space][space][space]
[space][space][space]Qty

Is there any solution for the above usecase?

**Comment by patkan** [comment] 2020-10-05 20:43
Hi, this looks like a duplicate of #27

**Closed by patkan** 2020-10-05 20:43 UTC
